"""Game constants and configuration values."""

# Screen constants
SCREEN_SIZE = (1000, 800)
DARK_GREY = (50, 50, 50)
YELLOW = (255, 204, 0)

# Player constants
PLAYER_START_X = 20
PLAYER_START_Y = 500
PLAYER_WIDTH = 52
PLAYER_HEIGHT = 72
PLAYER_MOVE_SPEED = 3
PLAYER_ACCELERATION = 0.1
PLAYER_GROUND_Y = 500
ENERGY_DECAY_MOVE = 0.017
ENERGY_DECAY_VERTICAL = 0.01
ENERGY_START = 10
ENERGY_BURGER_BONUS = 2

# Game constants
LIVES_START = 3
SCREEN_TOTAL = 2
BURGERS_REQUIRED = 2
FINISH_X_THRESHOLD = 880
FPS = 60

# File paths
IMAGE_DIR = 'images'
SOUND_DIR = 'sounds'

